package consts

type ERRORMESSAGE string

const (
	LEVELNOTFOUND         ERRORMESSAGE = "LEVEL DOES NOT EXIST AGAINST THIS ID"
	LEVELUPDATED                       = "Level Updated"
	LEVELDELETED                       = "LEVEL DELETED"
	LEVELSPACEERROR                    = "LEVEL CANNOT HAVE VALUE GREATER THEN 2 OR LESS THAN 0"
	LEVELLENGTHERROR                   = "LEVEL CANNOT HAVE DIMENSION GREATER THEN 100"
	LEVELRECTANGULARERROR              = "LEVEL IS NOT RECTANGULAR"
	PASSEDVALIDATIONS                  = ""
)
